# Generated by Django 5.2.8 on 2026-02-11 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicview', '0003_report_assigned_to_report_resolved_at_report_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_valid',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['is_valid'], name='report_is_valid_idx'),
        ),
    ]
