# Generated by Django 5.2.8 on 2026-02-11 16:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicview', '0004_report_is_valid_report_report_is_valid_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'counties',
                'indexes': [models.Index(fields=['name'], name='county_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailConstituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'Dáil constituency',
                'verbose_name_plural': 'Dáil constituencies',
                'indexes': [models.Index(fields=['name'], name='dail_constituency_name_idx')],
            },
        ),
    ]
