# Generated by Django 5.2.8 on 2026-03-17 13:48

import civicview.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicview', '0008_reportimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='supporters',
            field=models.ManyToManyField(blank=True, related_name='supported_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('moderator', 'Moderator'), ('staff', 'Staff'), ('council', 'Council'), ('manager', 'Manager'), ('admin', 'Admin')], default='citizen', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportimage',
            name='image',
            field=models.ImageField(upload_to=civicview.models.report_image_upload_to),
        ),
    ]
