# Import Django auth User model for report ownership
from django.conf import settings
# Import GeoDjango models for spatial database fields
from django.contrib.gis.db import models


# Report model: Stores individual civic issue reports submitted by users
# Each report contains text information, workflow state, and a geographic point location
class Report(models.Model):
    # Workflow status choices
    STATUS_OPEN = "open"
    STATUS_IN_PROGRESS = "in_progress"
    STATUS_RESOLVED = "resolved"
    STATUS_DISMISSED = "dismissed"

    STATUS_CHOICES = [
        (STATUS_OPEN, "Open"),
        (STATUS_IN_PROGRESS, "In progress"),
        (STATUS_RESOLVED, "Resolved"),
        (STATUS_DISMISSED, "Dismissed"),
    ]

    # Title of the civic issue report (e.g., "Streetlight out")
    title = models.CharField(max_length=200)
    # Detailed description of the issue
    description = models.TextField()
    # Category classification (e.g., "Lighting", "Potholes", "Graffiti")
    category = models.CharField(max_length=100)
    # Current workflow status for this report
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default=STATUS_OPEN,
        db_index=True,
    )
    # Geographic point location using WGS84 coordinate system (SRID 4326)
    # This allows spatial queries and distance calculations
    geom = models.PointField(srid=4326)
    # User who created the report (null for legacy reports; authenticated users set on create)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="reports",
    )
    # Optional assignee (typically council staff or moderator handling the report)
    assigned_to = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="assigned_reports",
    )
    # Optional target date for resolving this report
    target_resolution_date = models.DateField(null=True, blank=True)
    # Timestamp automatically set when the report is created
    created_at = models.DateTimeField(auto_now_add=True)
    # Timestamp when the report was marked as resolved (set when status changes to resolved)
    resolved_at = models.DateTimeField(null=True, blank=True)
    # Flag to indicate whether this report is considered valid (used for quality control)
    is_valid = models.BooleanField(default=True, db_index=True)

    class Meta:
        # Database indexes for faster queries on created_at, status, assignee, and validity
        indexes = [
            models.Index(fields=["created_at"], name="report_created_at_idx"),
            models.Index(fields=["status"], name="report_status_idx"),
            models.Index(fields=["assigned_to"], name="report_assigned_to_idx"),
            models.Index(fields=["is_valid"], name="report_is_valid_idx"),
        ]

    # String representation for admin interface and debugging
    def __str__(self):
        return f"{self.title} ({self.category})"


# ReportImage: Optional photo(s) attached to a report (e.g. from mobile app)
def report_image_upload_to(instance, filename):
    import uuid
    ext = filename.split(".")[-1] if "." in filename else "jpg"
    return f"report_images/{instance.report_id}/{uuid.uuid4().hex}.{ext}"


class ReportImage(models.Model):
    report = models.ForeignKey(
        Report,
        on_delete=models.CASCADE,
        related_name="images",
    )
    image = models.ImageField(upload_to=report_image_upload_to)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_at"]

    def __str__(self):
        return f"Image for report {self.report_id}"


# Hotspot model: Stores detected clusters of reports as polygon areas
# Generated by DBSCAN clustering algorithm to identify problem areas
class Hotspot(models.Model):
    # Unique identifier for the cluster (assigned by DBSCAN algorithm)
    cluster_id = models.IntegerField()
    # Polygon geometry representing the boundary of the hotspot cluster
    # Uses WGS84 coordinate system (SRID 4326) for consistency with Report points
    geom = models.PolygonField(srid=4326)
    # Timestamp automatically set when the hotspot is created
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        # Database indexes for faster queries by cluster_id and creation date
        indexes = [
            models.Index(fields=["cluster_id"], name="hotspot_cluster_idx"),
            models.Index(fields=["created_at"], name="hotspot_created_idx"),
        ]

    # String representation for admin interface and debugging
    def __str__(self):
        return f"Cluster {self.cluster_id}"


# County model: Stores administrative county boundaries for spatial analytics
class County(models.Model):
    # Human-readable county name (e.g., "Dublin", "Wexford")
    name = models.CharField(max_length=100, unique=True)
    # MultiPolygon geometry for the county boundary in WGS84
    boundary = models.MultiPolygonField(srid=4326)

    class Meta:
        verbose_name_plural = "counties"
        indexes = [
            models.Index(fields=["name"], name="county_name_idx"),
        ]

    def __str__(self):
        return self.name


# DáilConstituency model: Stores Dáil constituency boundaries for analytics
class DailConstituency(models.Model):
    # Constituency name (e.g., "Dublin South-West")
    name = models.CharField(max_length=150, unique=True)
    # MultiPolygon geometry for the constituency boundary in WGS84
    boundary = models.MultiPolygonField(srid=4326)

    class Meta:
        verbose_name = "Dáil constituency"
        verbose_name_plural = "Dáil constituencies"
        indexes = [
            models.Index(fields=["name"], name="dail_constituency_name_idx"),
        ]

    def __str__(self):
        return self.name


# Role choices for Profile
# citizen: general public, can report issues
# moderator: can edit/delete any report
# staff: council staff, can be assigned reports, see analytics/dashboard
# council: legacy, treated like staff (can be assigned, see dashboard)
# manager: can assign reports to staff, full workflow and admin-style access
# admin: full access including analytics/dashboard
class Profile(models.Model):
    ROLE_CITIZEN = "citizen"
    ROLE_MODERATOR = "moderator"
    ROLE_STAFF = "staff"
    ROLE_COUNCIL = "council"
    ROLE_MANAGER = "manager"
    ROLE_ADMIN = "admin"
    ROLE_CHOICES = [
        (ROLE_CITIZEN, "Citizen"),
        (ROLE_MODERATOR, "Moderator"),
        (ROLE_STAFF, "Staff"),
        (ROLE_COUNCIL, "Council"),
        (ROLE_MANAGER, "Manager"),
        (ROLE_ADMIN, "Admin"),
    ]
    # Roles that can be assigned to a report (staff, council, manager)
    ASSIGNABLE_ROLES = (ROLE_STAFF, ROLE_COUNCIL, ROLE_MANAGER)
    # Roles that can see dashboard/analytics
    DASHBOARD_ROLES = (ROLE_STAFF, ROLE_COUNCIL, ROLE_MANAGER, ROLE_ADMIN)
    # Roles that can set assigned_to on reports (manager, admin)
    CAN_ASSIGN_ROLES = (ROLE_MANAGER, ROLE_ADMIN)
    # Roles that can modify workflow fields (status, target_resolution_date, is_valid)
    WORKFLOW_ROLES = (ROLE_MODERATOR, ROLE_STAFF, ROLE_COUNCIL, ROLE_MANAGER, ROLE_ADMIN)

    # One-to-one link to Django User (created when user registers)
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="profile",
    )
    # Role: citizen (default), moderator, staff, council, manager, or admin
    role = models.CharField(max_length=20, choices=ROLE_CHOICES, default=ROLE_CITIZEN)

    def __str__(self):
        return f"{self.user.username} ({self.role})"


# In-app notification (e.g. "Report X assigned to you")
class Notification(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="notifications",
    )
    message = models.CharField(max_length=500)
    report = models.ForeignKey(
        Report,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="notifications",
    )
    read_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["user", "read_at"], name="notif_user_read_idx"),
        ]

    def __str__(self):
        return f"{self.user.username}: {self.message[:50]}"
