# Import Django REST Framework router and auth token view
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework.routers import DefaultRouter

from .analytics_views import (
    AnalyticsDashboardView,
    AnalyticsSummaryView,
    ConstituencyComparisonView,
    CountyComparisonView,
    GeographicReportsView,
)
from .auth_views import AssignableUsersView, MeView, RegisterView
from .notification_views import NotificationListView, NotificationMarkReadView
from .views import (
    CountyViewSet,
    DailConstituencyViewSet,
    HotspotViewSet,
    ReportViewSet,
)

# Create a router instance to automatically generate URL patterns
router = DefaultRouter()
# Register ReportViewSet at /api/reports/ endpoint
# Provides: GET /api/reports/ (list), POST /api/reports/ (create)
#           GET /api/reports/{id}/ (detail), PUT/PATCH /api/reports/{id}/ (update)
#           DELETE /api/reports/{id}/ (delete)
#           GET /api/reports/categories/ (distinct categories for filter)
router.register(r"reports", ReportViewSet, basename="report")
# Register HotspotViewSet at /api/hotspots/ endpoint
# Provides: GET /api/hotspots/ (list), GET /api/hotspots/{id}/ (detail)
# Note: Hotspots are read-only (auto-generated by clustering algorithm)
router.register(r"hotspots", HotspotViewSet, basename="hotspot")
# Register CountyViewSet at /api/counties/ endpoint (council/admin only)
router.register(r"counties", CountyViewSet, basename="county")
# Register DailConstituencyViewSet at /api/constituencies/ endpoint (council/admin only)
router.register(r"constituencies", DailConstituencyViewSet, basename="constituency")

# Auth and analytics (council/admin only for analytics)
urlpatterns = router.urls + [
    path("auth/login/", obtain_auth_token, name="api_token_auth"),
    path("auth/register/", RegisterView.as_view(), name="api_register"),
    path("auth/me/", MeView.as_view(), name="api_me"),
    path("auth/assignable-users/", AssignableUsersView.as_view(), name="api_assignable_users"),
    path("notifications/", NotificationListView.as_view(), name="api_notifications_list"),
    path("notifications/<int:pk>/read/", NotificationMarkReadView.as_view(), name="api_notifications_mark_read"),
    path("analytics/summary/", AnalyticsSummaryView.as_view(), name="api_analytics_summary"),
    path("analytics/dashboard/", AnalyticsDashboardView.as_view(), name="api_analytics_dashboard"),
    path("analytics/county-comparison/", CountyComparisonView.as_view(), name="api_county_comparison"),
    path("analytics/constituency-comparison/", ConstituencyComparisonView.as_view(), name="api_constituency_comparison"),
    path("analytics/geographic-reports/", GeographicReportsView.as_view(), name="api_geographic_reports"),
]


